import PDFDocument from "pdfkit";
import type { ReportData } from "@/lib/report";

const NAVY = "#1f2a44";
const GRAY = "#6b7280";
const LINE = "#d1d5db";

const GROUP_NOUN: Record<string, string> = { job: "Job", employee: "Employee", code: "Labor Code" };

// Column layout (x offsets and widths) within the content area.
const COLS = {
  date: { x: 36, w: 70 },
  emp: { x: 110, w: 130 },
  code: { x: 244, w: 150 },
  desc: { x: 398, w: 120 },
  hours: { x: 522, w: 54 }, // right edge ~576 (LETTER 612 - 36 margin)
};

/**
 * QuickBooks "Time by X Detail" style PDF, built with pdfkit (no React).
 * Company header, grouped sections with subtotals, grand total, footer.
 */
export async function renderReportPdf(data: ReportData, companyName: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: 36, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const right = 576;
    const bottom = 740;

    const ensureSpace = (need: number) => {
      if (doc.y + need > bottom) doc.addPage();
    };

    // Header
    doc.fillColor(NAVY).font("Helvetica-Bold").fontSize(18).text(companyName, 36, 36);
    doc.fillColor(GRAY).font("Helvetica").fontSize(8).text("Job costing report", 36, 58);

    doc.fillColor(NAVY).font("Helvetica-Bold").fontSize(13).text(`Time by ${GROUP_NOUN[data.groupBy]} Detail`, 36, 76);
    doc.fillColor(GRAY).font("Helvetica").fontSize(9).text(`${data.startLabel} to ${data.endLabel}  .  approved hours only`, 36, 94);

    doc.y = 116;

    const drawColHeader = () => {
      const y = doc.y;
      doc.fillColor(NAVY).font("Helvetica-Bold").fontSize(8);
      doc.text("Date", COLS.date.x, y, { width: COLS.date.w });
      doc.text("Employee", COLS.emp.x, y, { width: COLS.emp.w });
      doc.text("Code", COLS.code.x, y, { width: COLS.code.w });
      doc.text("Description", COLS.desc.x, y, { width: COLS.desc.w });
      doc.text("Hours", COLS.hours.x, y, { width: COLS.hours.w, align: "right" });
      doc.moveTo(36, y + 12).lineTo(right, y + 12).strokeColor(LINE).lineWidth(0.5).stroke();
      doc.y = y + 16;
    };

    for (const g of data.groups) {
      ensureSpace(60);
      // group header bar
      const gy = doc.y;
      doc.rect(36, gy, right - 36, 16).fill(NAVY);
      doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(9).text(g.label, 40, gy + 4, { width: 420 });
      doc.text(`${g.subtotal.toFixed(2)} h`, COLS.hours.x - 40, gy + 4, { width: COLS.hours.w + 40, align: "right" });
      doc.y = gy + 20;

      drawColHeader();

      doc.font("Helvetica").fontSize(8).fillColor("#1f2937");
      for (const r of g.rows) {
        ensureSpace(16);
        const y = doc.y;
        doc.fillColor("#1f2937");
        doc.text(r.date, COLS.date.x, y, { width: COLS.date.w });
        doc.text(r.employee, COLS.emp.x, y, { width: COLS.emp.w });
        doc.text(r.code || "-", COLS.code.x, y, { width: COLS.code.w });
        doc.text(r.description || "-", COLS.desc.x, y, { width: COLS.desc.w });
        doc.text(r.hours.toFixed(2), COLS.hours.x, y, { width: COLS.hours.w, align: "right" });
        doc.y = y + 13;
        doc.moveTo(36, doc.y - 2).lineTo(right, doc.y - 2).strokeColor("#eef0f3").lineWidth(0.5).stroke();
      }
      ensureSpace(20);
      doc.font("Helvetica-Bold").fontSize(8).fillColor(NAVY);
      doc.text(`Subtotal: ${g.subtotal.toFixed(2)} h`, COLS.code.x, doc.y + 2, { width: right - COLS.code.x, align: "right" });
      doc.y += 22;
    }

    ensureSpace(30);
    doc.moveTo(36, doc.y).lineTo(right, doc.y).strokeColor(NAVY).lineWidth(1).stroke();
    doc.font("Helvetica-Bold").fontSize(11).fillColor(NAVY);
    doc.text(`Grand total: ${data.grandTotal.toFixed(2)} h`, 36, doc.y + 6, { width: right - 36, align: "right" });

    // Footer on every page
    const range = doc.bufferedPageRange();
    const generatedAt = new Date().toLocaleString("en-US");
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.font("Helvetica").fontSize(7).fillColor(GRAY);
      doc.text(`Generated ${generatedAt}`, 36, 756, { width: 300 });
      doc.text(`Generated by ${companyName} Timesheets`, 276, 756, { width: 300, align: "right" });
    }

    doc.end();
  });
}
